version: '3.2'

services:

  trena:
    build: ./trena
    ports:
      - "5548:5548"
    volumes:
      - type: volume
        source: sharedData
        target: /home/trena/tmp

  nbserver:
    build: ./nbserver
    command:  start-notebook.sh --NotebookApp.base_url=/ --port=8888 --NotebookApp.token=
    ports:
      - "8888:8888"
    volumes:
      - type: volume
        source: sharedData
        target: /home/jovyan/mef2c/tmp
      - "/notebooks:/home/jovyan/mef2c/notebooks"

volumes:
    sharedData:
