FROM rocker/rstudio
COPY .  /home/rstudio/
RUN cat /home/rstudio/myBashCustomizations >> /home/rstudio/.bashrc
RUN cat /home/rstudio/myRprofile >> /home/rstudio/.Rprofile
user rstudio
WORKDIR /home/rstudio
RUN mkdir library
RUN R -f installTrenaPrequisites-01.R
user root
CMD ["/init"]
